"""Dark professional theme: Fusion style + QSS (Blender/VSCode-flavored).

The QSS is built per font size via ``build_qss`` — ``apply_theme`` uses
the default, ``set_font_size`` re-applies live (Preferences → General).

Rules of thumb kept here:
- No universal ``QWidget { background }`` — the QPalette Window role
  paints plain widgets; explicit backgrounds only where panels need to
  differ from the base (the old universal rule caused dark rectangles
  behind every label).
- ``QGroupBox::title`` needs ``background: transparent`` (the classic
  square-patch artifact otherwise).
- Widgets that need a themed look carry an objectName (``#danger``,
  ``#readout``, ``#dim``, ``#ok``, ``#mode_badge``, ``#log``, …) —
  inline ``setStyleSheet`` calls with hardcoded colors are banned.
"""

from __future__ import annotations

from PySide6.QtGui import QColor, QPalette
from PySide6.QtWidgets import QApplication

from talos.paths import resource_path

# Palette — NEUTRAL dark surfaces (the VSCode gray family, no blue
# cast) with the WULING TEAL accent by default (the user's pick).
# The accent is user-configurable via ACCENT_GROUPS, see set_accent.
BG = "#1e1e1e"
PANEL = "#252526"
PANEL_ALT = "#2d2d30"
BORDER = "#3f3f46"
TEXT = "#d4d4d4"
TEXT_DIM = "#9b9b9b"
ACCENT = "#00BCBC"
ACCENT_DARK = "#008686"
OK = "#3fb950"
WARN = "#d29922"
DANGER = "#f85149"
LED_OFF = "#3a3a3a"

_DEFAULT_FONT_SIZE = 12
_current_font_size = _DEFAULT_FONT_SIZE

# The QSS image glyphs (resources/qss/) — Qt's stylesheet loader cannot
# take data: URIs, so they ship as real bundled files (the arrows are
# checked in; the checkbox dot is generated by tools/make_qss_assets.py).
_up_arrow = str(resource_path("resources/qss/arrows_up.png")).replace("\\", "/")
_down_arrow = str(resource_path("resources/qss/arrows_down.png")).replace("\\", "/")
_check_dot = str(resource_path("resources/qss/checkbox_dot.png")).replace("\\", "/")
_combo_arrow = str(resource_path("resources/qss/combo_arrow.png")).replace("\\", "/")

# (name, accent, accent_dark) — the flat pair list behind the accent
# combo. The Endfield darks are QColor.darker(140) of the user-mandated
# hexes; the Warhammer darks are hand-tuned for dark surfaces. A custom
# hex derives its dark via QColor.darker(140) (see accent_dark_for).
ACCENT_PRESETS = (
    ("Endfield", "#FFFA00", "#b6b300"),
    ("Valley IV", "#D0E300", "#95a200"),
    ("Wuling", "#00BCBC", "#008686"),
    ("Khorne", "#e5484d", "#b0353a"),
    ("Tzeentch", "#6f7bff", "#545ec7"),
    ("Nurgle", "#7cb342", "#5c8730"),
    ("Slaanesh", "#ce6dd6", "#9a4fa0"),
)

# The accent combo's display structure: disabled group headers above
# their preset items (the "Custom…" tail is added by the dialog).
ACCENT_GROUPS = (
    ("Endfield", ("Endfield", "Valley IV", "Wuling")),
    ("Warhammer", ("Khorne", "Tzeentch", "Nurgle", "Slaanesh")),
)


def accent_dark_for(accent_hex: str) -> str:
    """The paired dark for a preset match, else a fixed darken factor."""
    for _name, accent, dark in ACCENT_PRESETS:
        if accent_hex.strip().lower() == accent.lower():
            return dark
    color = QColor(accent_hex)
    return color.darker(140).name() if color.isValid() else ACCENT_DARK


def build_qss(font_size_px: int = _DEFAULT_FONT_SIZE,
              accent: str = ACCENT, accent_dark: str = ACCENT_DARK) -> str:
    px = max(8, min(int(font_size_px), 16))
    accent_color = QColor(accent)
    accent_light = accent_color.lighter(115).name()
    # perceived luminance (BT.601) picks the primary-button text —
    # QColor.lightness() misorders saturated hues (a bright yellow reads
    # "dark" to it, giving white-on-yellow). Dark text below luma ~128.
    luma = (0.299 * accent_color.red() + 0.587 * accent_color.green()
            + 0.114 * accent_color.blue())
    primary_text = "#17181d" if luma > 128 else "#ffffff"
    return f"""
* {{
    font-family: "Segoe UI", "Microsoft YaHei", sans-serif;
    font-size: {px}px;
    color: {TEXT};
}}
QMainWindow, QDialog {{ background: {BG}; }}
QMenuBar {{
    background: {PANEL};
    border-bottom: 1px solid {BORDER};
}}
QMenuBar::item {{
    background: transparent;
    padding: 6px 12px;
    font-size: {px + 1}px;
}}
QMenuBar::item:selected {{ background: {PANEL_ALT}; border-radius: 3px; }}
QMenu {{
    background: {PANEL_ALT};
    border: 1px solid {BORDER};
    padding: 4px 0;
}}
QMenu::item {{ padding: 5px 26px 5px 22px; }}
QMenu::item:selected {{ background: {accent_dark}; color: #ffffff; }}
QMenu::separator {{ height: 1px; background: {BORDER}; margin: 4px 8px; }}
QToolBar {{ background: {PANEL}; border-bottom: 1px solid {BORDER}; }}
QToolTip {{
    background: {PANEL_ALT};
    color: {TEXT};
    border: 1px solid {BORDER};
    padding: 4px 8px;
}}
QGroupBox {{
    border: 1px solid {BORDER};
    border-radius: 5px;
    margin-top: 9px;
    padding: 6px;
    background: {PANEL};
    font-weight: 600;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    left: 8px;
    padding: 0 3px;
    background: transparent;
    color: {TEXT};
    font-weight: 700;
    letter-spacing: 1px;
}}
QWidget#collapsible {{
    border: 1px solid {BORDER};
    border-radius: 5px;
    background: {PANEL};
}}
QPushButton#collapsible_header {{
    text-align: left;
    border: none;
    background: transparent;
    padding: 4px 2px;
    color: {TEXT};
    font-weight: 700;
    letter-spacing: 1px;
}}
QPushButton#collapsible_header:hover {{ color: {accent_color.name()}; }}
QPushButton#collapsible_header:checked {{
    color: {TEXT};
    border-bottom: 1px solid {BORDER};
}}
QTabWidget::pane {{
    border: 1px solid {BORDER};
    border-radius: 4px;
    background: {PANEL};
    top: -1px;
}}
QTabBar::tab {{
    background: transparent;
    padding: 6px 16px;
    border: 1px solid transparent;
    color: {TEXT_DIM};
    font-size: {px + 1}px;
    font-weight: 700;
}}
QTabBar::tab:selected {{
    background: {PANEL};
    color: {TEXT};
    border: 1px solid {BORDER};
    border-bottom: 2px solid {accent};
}}
QTabBar::tab:hover:!selected {{ color: {TEXT}; }}
QPushButton {{
    background: {PANEL_ALT};
    border: 1px solid {BORDER};
    border-radius: 4px;
    padding: 4px 10px;
    min-width: 32px;
}}
QPushButton:hover {{ border-color: {accent}; }}
QPushButton:pressed {{ background: {accent_dark}; }}
QPushButton:disabled {{ color: #565b68; border-color: #2c2f37; }}
QPushButton#compact {{
    padding: 3px 6px;
    min-width: 24px;
}}
QPushButton#qa, QPushButton#qa_primary {{
    font-size: {px + 1}px;
    font-weight: 700;
    padding: 6px 12px;
}}
QPushButton#qa_primary {{
    background: {accent};
    color: {primary_text};
    border: 1px solid {accent_dark};
}}
QPushButton#qa_primary:hover {{ background: {accent_light}; }}
QPushButton#qa_primary:pressed {{ background: {accent_dark}; }}
QFrame#card {{
    border: 1px solid {BORDER};
    border-radius: 5px;
    background: {PANEL};
}}
QWidget#segmented {{
    border: 1px solid {BORDER};
    border-radius: 4px;
    /* A surface, like the hover bar: on the panel's near-black the
       unselected segments read as gaps rather than as options. */
    background: {PANEL_ALT};
}}
QPushButton#segmented_btn {{
    background: transparent;
    border: none;
    border-right: 1px solid {BORDER};
    border-radius: 0;
    padding: 4px 8px;
    min-width: 0;
}}
QPushButton#segmented_btn:last-child {{ border-right: none; }}
QPushButton#segmented_btn:hover {{ color: {accent}; }}
QPushButton#segmented_btn:checked {{
    background: {accent};
    color: {primary_text};
    font-weight: 700;
}}
QPushButton#segmented_btn:disabled {{ color: #565b68; }}
QFrame#hoverbar {{
    border: 1px solid {BORDER};
    border-radius: 4px;
    background: {PANEL_ALT};
}}
QPushButton#hoverbar_btn {{
    background: transparent;
    border: none;
    padding: 2px 8px;
    min-width: 0;
}}
QPushButton#hoverbar_btn:hover {{ color: {accent}; }}
QPushButton#hoverbar_btn:checked {{
    background: {accent};
    color: {primary_text};
    font-weight: 700;
    border-radius: 3px;
}}
QPushButton#danger {{
    background: {DANGER};
    color: #ffffff;
    font-weight: 700;
    border: none;
    padding: 6px 18px;
    font-size: {px + 1}px;
}}
QPushButton#danger:hover {{ background: #ff6b63; }}
QPushButton#danger:pressed {{ background: #c93b33; }}
/* A disabled danger button must not look armed: the AF Abort and STOP ALL
   buttons are red at all times otherwise, including while inactive. */
QPushButton#danger:disabled {{
    background: #3a2b2b;
    color: #7a6a6a;
}}
QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox {{
    background: {BG};
    border: 1px solid #3c3c3c;
    border-radius: 3px;
    padding: 2px 6px;
    selection-background-color: {accent_dark};
}}
QLineEdit:hover, QComboBox:hover, QSpinBox:hover, QDoubleSpinBox:hover {{
    border-color: #4a4a4a;
}}
QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus {{
    border-color: {accent};
}}
QComboBox::drop-down {{ border: none; width: 18px; }}
/* Without an explicit image every combo renders as a plain box: styling
   the drop-down switches Qt to stylesheet-drawn subcontrols, which have
   no default arrow (the port/baudrate pickers made this obvious). */
QComboBox::down-arrow {{
    image: url("{_combo_arrow}");
    width: 9px;
    height: 6px;
}}
QSpinBox::up-button, QDoubleSpinBox::up-button,
QSpinBox::down-button, QDoubleSpinBox::down-button {{
    background: {PANEL_ALT};
    border-left: 1px solid {BORDER};
    width: 16px;
}}
QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover,
QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover {{
    background: #3a3a3d;
}}
QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed,
QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed {{
    background: {accent_dark};
}}
QSpinBox::up-arrow, QDoubleSpinBox::up-arrow {{
    image: url({_up_arrow});
    width: 9px;
    height: 9px;
}}
QSpinBox::down-arrow, QDoubleSpinBox::down-arrow {{
    image: url({_down_arrow});
    width: 9px;
    height: 9px;
}}
QComboBox#objective {{
    font-size: {px + 1}px;
    font-weight: 700;
    padding: 3px 10px;
    min-width: 110px;
}}
QComboBox QAbstractItemView {{
    background: {PANEL_ALT};
    border: 1px solid {BORDER};
    selection-background-color: {accent_dark};
    selection-color: #ffffff;
    outline: none;
}}
QCheckBox {{ spacing: 6px; }}
QCheckBox::indicator {{
    width: 14px;
    height: 14px;
    border: 1px solid {BORDER};
    border-radius: 4px;
    background: {BG};
}}
QCheckBox::indicator:hover {{ border-color: {accent}; }}
QCheckBox::indicator:checked {{
    background: {accent_dark};
    border-color: {accent};
    image: url({_check_dot});
    image-position: center;
}}
QSlider::groove:horizontal {{ height: 4px; background: {BORDER}; border-radius: 2px; }}
QSlider::handle:horizontal {{
    background: {accent};
    width: 12px;
    margin: -4px 0;
    border-radius: 6px;
}}
QProgressBar {{
    background: {BG};
    border: 1px solid {BORDER};
    border-radius: 3px;
    text-align: center;
    color: {TEXT_DIM};
}}
QProgressBar::chunk {{ background: {accent_dark}; border-radius: 2px; }}
QTableView {{
    background: {BG};
    alternate-background-color: {PANEL};
    gridline-color: {BORDER};
    border: 1px solid {BORDER};
}}
QTreeWidget#prefs_nav {{
    background: {PANEL};
    border: 1px solid {BORDER};
    border-radius: 4px;
}}
QTreeWidget#prefs_nav::item {{
    padding: 4px 6px;
    /* transparent palette highlight — the base style would paint its
       square Highlight rect UNDER the rounded :selected background,
       doubling the selection (sharp corners behind the rounded one) */
    selection-background-color: transparent;
}}
QTreeWidget#prefs_nav::item:selected {{
    background: {accent_dark};
    color: #ffffff;
    border-radius: 3px;
    outline: none;
}}
QHeaderView::section {{
    background: {PANEL_ALT};
    border: none;
    border-right: 1px solid {BORDER};
    padding: 3px 6px;
}}
QStatusBar {{
    background: {PANEL};
    border-top: 1px solid {BORDER};
}}
QStatusBar::item {{ border: none; }}
QStatusBar QLabel {{ color: {TEXT_DIM}; }}
QSplitter::handle {{ background: {BORDER}; }}
QSplitter::handle:horizontal {{ width: 5px; }}
QSplitter::handle:vertical {{ height: 5px; }}
QSplitter::handle:hover {{ background: {accent_dark}; }}
QScrollArea {{ border: none; background: transparent; }}
QScrollArea QWidget#qt_scrollarea_viewport {{ background: transparent; }}
QScrollBar:vertical {{ background: transparent; width: 10px; margin: 0; }}
QScrollBar::handle:vertical {{
    background: {BORDER};
    border-radius: 5px;
    min-height: 24px;
}}
QScrollBar:horizontal {{ background: transparent; height: 10px; margin: 0; }}
QScrollBar::handle:horizontal {{
    background: {BORDER};
    border-radius: 5px;
    min-width: 24px;
}}
QScrollBar::add-line, QScrollBar::sub-line {{ width: 0; height: 0; }}
QScrollBar::add-page, QScrollBar::sub-page {{ background: transparent; }}
QLabel#dim {{ color: {TEXT_DIM}; }}
QLabel#ok {{ color: {OK}; }}
QLabel#hint {{ color: {TEXT_DIM}; }}
QLabel#mode_badge {{
    background: {PANEL_ALT};
    color: {TEXT_DIM};
    padding: 3px 8px;
    border-radius: 3px;
    font-weight: 700;
}}
QLabel#readout {{
    font-family: "Consolas", monospace;
    color: {accent};
    background: {BG};
    border: 1px solid {BORDER};
    border-radius: 3px;
    padding: 2px 6px;
}}
QLabel#liveview {{
    color: {TEXT_DIM};
    border: 1px solid {BORDER};
    /* NO background — an opaque label would bury the parent's
       paintEvent overlays (scale bar, crosshair, AF indicator). */
}}
QTextEdit#log {{
    background: {BG};
    border: 1px solid {BORDER};
    font-family: "Consolas", monospace;
}}
/* Hardware strip (the bottom instrument bar): framed sections plus the
   two condition indicators that used to be inline stylesheets. */
QFrame#strip_section {{
    border: 1px solid {BORDER};
    border-radius: 4px;
    background: {PANEL};
}}
QLabel#strip_mov {{ color: {OK}; font-weight: 700; }}
QLabel#strip_mov_idle {{ color: {TEXT_DIM}; }}
QLabel#strip_estop {{ color: {DANGER}; font-weight: 700; }}
QLabel#strip_warn {{ color: {WARN}; font-weight: 700; }}
"""


def apply_theme(app: QApplication) -> None:
    app.setStyle("Fusion")
    palette = QPalette()
    palette.setColor(QPalette.ColorRole.Window, QColor(BG))
    palette.setColor(QPalette.ColorRole.WindowText, QColor(TEXT))
    palette.setColor(QPalette.ColorRole.Base, QColor(BG))
    palette.setColor(QPalette.ColorRole.AlternateBase, QColor(PANEL))
    palette.setColor(QPalette.ColorRole.Text, QColor(TEXT))
    palette.setColor(QPalette.ColorRole.Button, QColor(PANEL_ALT))
    palette.setColor(QPalette.ColorRole.ButtonText, QColor(TEXT))
    palette.setColor(QPalette.ColorRole.Highlight, QColor(ACCENT_DARK))
    palette.setColor(QPalette.ColorRole.HighlightedText, QColor("#ffffff"))
    palette.setColor(QPalette.ColorRole.PlaceholderText, QColor(TEXT_DIM))
    app.setPalette(palette)
    global _current_font_size
    _current_font_size = _DEFAULT_FONT_SIZE
    app.setStyleSheet(build_qss())


def set_font_size(app: QApplication, px: int) -> None:
    """Re-apply the stylesheet at a new base font size (live re-theme)."""
    global _current_font_size
    _current_font_size = max(8, min(int(px), 16))
    app.setStyleSheet(build_qss(_current_font_size, ACCENT, ACCENT_DARK))


def set_accent(app: QApplication, accent_hex: str,
               accent_dark: str | None = None) -> str:
    """Apply an accent color live (validated). Returns the applied hex,
    or the current ACCENT when the input is invalid."""
    global ACCENT, ACCENT_DARK
    color = QColor(accent_hex)
    if not color.isValid():
        return ACCENT
    ACCENT = color.name()
    ACCENT_DARK = accent_dark or accent_dark_for(ACCENT)
    palette = app.palette()
    palette.setColor(QPalette.ColorRole.Highlight, QColor(ACCENT_DARK))
    app.setPalette(palette)
    app.setStyleSheet(build_qss(_current_font_size, ACCENT, ACCENT_DARK))
    return ACCENT
