"""The QSS image glyphs the stylesheet references must exist — and ship.

Qt's stylesheet loads them at RUNTIME by path: a missing file is a
console warning, not an error, so the widget simply loses its affordance
(the spin arrows, the checkbox dot, the combo chevron). The frozen build
needs them in `datas` for the same reason — that is what this test pins.
"""

import re
from pathlib import Path

from talos.ui import theme

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _referenced_assets() -> list[str]:
    qss = theme.build_qss()
    return re.findall(r'url\("([^"]+)"\)', qss)


def test_every_referenced_qss_asset_exists():
    assets = _referenced_assets()
    assert assets, "the stylesheet references no image assets?"
    for path in assets:
        assert Path(path).is_file(), f"missing QSS asset: {path}"


def test_qss_assets_are_bundled_by_the_packaging_spec():
    """A frozen build resolves resource_path() to sys._MEIPASS — the spec
    must put resources/qss there or the EXE silently loses the glyphs."""
    spec = (_REPO_ROOT / "packaging" / "talos.spec").read_text(encoding="utf-8")
    assert '"qss"' in spec and "resources/qss" in spec

    # every asset lives under resources/qss (so one datas entry covers them)
    for path in _referenced_assets():
        assert Path(path).parent.name == "qss", path


def test_combo_chevron_asset_is_real_png():
    """Generated by tools/make_qss_assets.py — a zero-byte or text file
    would make Qt drop the subcontrol image silently."""
    from talos.paths import resource_path

    arrow = resource_path("resources/qss/combo_arrow.png")
    assert arrow.is_file()
    data = arrow.read_bytes()
    assert data.startswith(b"\x89PNG\r\n\x1a\n") and len(data) > 60
